name: ci_cmake

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran liblapack-dev

    - run: ctest -S setup.cmake -VV
