name: ci_cmake

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install -yq --no-install-recommends gfortran liblapack-dev
    - run: mkdir build
    - run: cmake ..
      working-directory: build
    - run: cmake --build build --parallel
    - run: cmake --build build --target test
